### ISSUE TITLE
Does plugin-paypalexpress supercede plugin-paypal?

### ISSUE THREAD

**Issue by modius** [farcrycore/plugin-paypalexpress#1]
What is the difference between this plugin and https://github.com/farcrycore/plugin-paypal

Is `plugin-paypal` being deprecated in favour of this plugin?

**Comment by justincarter** [comment]
This plugin is for PayPal Express, the other is for PayPal PayFlow Pro. The readme file will explain this but its only half written right now.

-----Original Message-----
